<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>promise</title>
</head>

<body>
  <script>
    // 自定义Promise函数模块：IIFE
    (function (window) {
      // Promise构造函数
      // excutor:执行器函数
      const PENDING = 'pending'
      const RESOLVED = 'resolved'
      const REJECTED = 'rejected'

      function Promise(excutor) {
        this.status = PENDING // 给promise对象那个指定status属性，初始值为pending
        this.data = undefined // 给promise对象指定一个用于存储结果数据的属性
        this.callbacks = [] // 每个元素的结构：{onResolved(){},onRejected(){}}
        const self = this

        function resolve(value) {
          if (self.status !== PENDING) return
          // 将状态改为resolved
          self.status = RESOLVED
          // 保存value数据
          self.data = value
          // 如果有待执行callback函数，立即异步执行回调函数onResolved
          if (self.callbacks.length > 0) {
            setTimeout(() => {
              self.callbacks.forEach(callBackObj => {
                callBackObj.onResolved(value)
              });
            })
          }

        }

        function reject(reason) {
          if (self.status !== PENDING) return
          // 将状态改为rejected
          self.status = REJECTED
          // 保存reason数据
          self.data = reason
          // 如果有待执行callback函数，立即异步执行回调函数onRejected
          if (self.callbacks.length > 0) {
            setTimeout(() => {
              self.callbacks.forEach(callbacksObj => {
                callbacksObj.onRejected(reason)
              });
            })
          }
        }
        // 立即 同步执行excutor
        try {
          // (resolve, reject) => {
          //   setTimeout(() => {
          //     resolve(1);
          //     // reject(1);
          //   }, 100)
          // }
          excutor(resolve, reject)
        } catch (error) {
          // 如果执行器抛出异常，promise对象变为rejected状态
          reject(error)
        }
      }
      /* 
      Promise原型对象的then()
      指定成功和失败的回调函数
      返回一个新的promise对象
      */
      Promise.prototype.then = function (onResolved, onRejected) {
        onResolved = typeof onResolved === 'function' ? onResolved : value => value //向后传递成功的value
        // 指定默认的失败的回调（实现错误/异常穿透的关键点）
        onRejected = typeof onRejected === 'function' ? onRejected : reason => {
          throw reason
        } //向后传递失败的reason

        const self = this
        // 返回一个promise对象
        return new Promise((resolve, reject) => {
          /* 
           调用指定回调函数处理，根据执行结果，改变return的promsie的状态
          */
          function handle(callback) {
            /*  
              1、如果抛出异常，return的promise就会失败，reason就是error
              2、如果回调函数返回不是promise,return的promsie就会成功，value就是返回的值
              3、如果回调函数返回是promsie,return的promsie结果就是这个promise的结果
            */
            try {
              const result = callback(self.data)
              // 3、如果回调函数返回是promsie,return的promsie结果就是这个promise的结果
              // 把return promise的结果传递给 后面的then
              if (result instanceof Promise) {
                result.then(
                  value => {
                    resolve(value)
                  }, //当result成功时，让return的promsie也成功
                  reason => reject(reason) //当result失败时，让return的promise也失败
                )
                // resolve(result) 

                // result.then(
                //   function (value) {
                //     return resolve(value)
                //   },
                //   function (reason) {
                //     return reject(reason)
                //   }
                // )
                // result.then(resolve, reject)
              } else {
                // 2、如果回调函数返回不是promise,return的promsie就会成功，value就是返回的值
                resolve(result)
              }

            } catch (error) {
              // 1、如果抛出异常，return的promise就会失败，reason就是error
              reject(error)
            }
          }
          if (self.status == PENDING) {
            // 当前状态还是pending状态，将回调函数保存起来
            self.callbacks.push({
              onResolved() {
                handle(onResolved)
              },
              onRejected() {
                handle(onRejected)
              }
            })
          } else if (self.status == RESOLVED) { //如果当前是resolved状态，异步执行onResolve并改变return的promise状态
            setTimeout(() => {
              handle(onResolved)
            })
          } else {
            setTimeout(() => {
              handle(onRejected)
            })
          }

        })
      }
      /* 
       Promise原型对象的catch()
       指定失败的回调函数
       返回一个新的promise对象
      */
      Promise.prototype.catch = function (onRejected) {
        return this.then(undefined, onRejected)
      }
      /* 
       Promise函数的resolve方法
       返回一个指定value的成功promise
      */
      Promise.resolve = function (value) {
        // 返回一个成功/失败的promise
        return new Promise((resolve, reject) => {
          // value是promsie
          if (value instanceof Promise) { //使用value的结果作为promise的结果
            value.then(resolve, reject)
          } else { // value不是promsie
            resolve(value)
          }
        })
      }
      /* 
       Promise函数的reject方法
       返回一个指定reason的失败promise
      */
      Promise.reject = function (reason) {
        // 返回一个失败的promise
        return new Promise((resolve, reject) => {
          reject(reason)
        })
      }
      /* 
       Promise函数对象的all方法
       返回一个promise，只有当所有promise都成功时才成功，否则有一个失败的就失败
      */
      Promise.all = function (promises) {
        let values = new Array(promises.length);//用来保存所有成功的values数组
        let valueCount = 0
        return new Promise((resolve, reject) => {
          promises.forEach((p, index) => {
            Promise.resolve(p).then((value) => {
              valueCount++ //成功数量加1
              // p成功，将成功的values保存到values中
              values[index] = value
              // 如果全部成功了，将return的promise改变为成功
              if (valueCount == promises.length) {
                resolve(values)
              }
            }, reason => {
              // 只要有一个失败了，return的promise就失败
              reject(reason)
            })
          })
        })

      }
      /* 
       Promise函数对象的race方法
       返回一个promise，其结果由第一个完成的promsie决定
      */
      Promise.race = function (promises) {
        // 返回一个promise
        return new Promise((resolve, reject) => {
          // 遍历promises获取每个promise的结果
          promises.forEach(p => {
            Promise.resolve(p).then((value) => { //一旦成功了,将return的promise变为成功
              resolve(value)
            }, reason => { //一旦失败了，将return的promise变为失败
              reject(reason)
            })
          })
        })
      }
      /* 向外暴露Promise函数  */
      window.Promise2 = Promise
    })(window)
  </script>
  <script>
    // const p = new Promise((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve('成功');
    //     // reject('shibai');
    //   }, 1000)
    // })
    // let childP = p.then((value) => {
    //   console.log(value)
    //   return value
    // })
    // console.log(p);
    // console.log(childP) //fulfilled状态的Promise

    // 自定义Promise函数模块
    // 测试promsie
    // const p = new Promise2((resolve, reject) => {
    //   setTimeout(() => {
    //     resolve(1);
    //     // reject(1);
    //   }, 100)
    // })
    // p.then(value => {
    //   return new Promise2((resolve2, reject2) => {
    //     resolve2(2)
    //   })
    // }).then(value => {
    //   console.log(value, 'value2')
    // }, reason => {
    //   console.log(reason, 'reason2')
    // })
    const p1 = Promise2.resolve(1); //如果是一般值，p1成功，value就是这个值
    const p2 = Promise2.resolve(Promise2.resolve(2)); //如果是成功的promise，p2成功，value是这个promise的value
    const p3 = Promise2.resolve(Promise2.reject(3)); //如果是失败的primise,p3失败，reason是这个promise的reason
    // p1.then(value => {
    //   console.log(value, 1)
    // })
    p2.then(value => {
      console.log(value, 2)
    })
    // p3.then(value => {
    //   console.log(value, 3)
    // }, reason => {
    //   console.log(reason, 3)
    // })
    // Promise2.all([p1, 'hhhh', p2]).then(values => {
    //   console.log(values, '成功')
    // }, reason => {
    //   console.log(reason, '失败')
    // })
    // const p4 = Promise2.reject(1);
    // Promise2.race([p4, p1, p2, p3, 'hh']).then(values => {
    //   console.log(values, '成功')
    // }, reason => {
    //   console.log(reason, '失败')
    // })
  </script>
</body>

</html>